development:
  adapter: postgresql
  database: ajax_development
  user: postgres
  password: postgres
  host: localhost

test:
  adapter:  postgresql
  database:  ajax_test
  user: postgres
  password: postgres
  host: localhost
